# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filewidget.ui'
#
# Created: Sun Jan  3 21:04:53 2010
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(588, 580)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setMargin(10)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 7, 2, 1, 1)
        self.tagsBox = QtGui.QGroupBox(Dialog)
        self.tagsBox.setFlat(False)
        self.tagsBox.setCheckable(True)
        self.tagsBox.setObjectName("tagsBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.tagsBox)
        self.gridLayout_2.setMargin(10)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEditTags = QtGui.QLineEdit(self.tagsBox)
        self.lineEditTags.setObjectName("lineEditTags")
        self.gridLayout_2.addWidget(self.lineEditTags, 4, 0, 1, 3)
        self.tags_mergeButton = QtGui.QPushButton(self.tagsBox)
        self.tags_mergeButton.setObjectName("tags_mergeButton")
        self.gridLayout_2.addWidget(self.tags_mergeButton, 6, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(self.tagsBox)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 6, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 6, 0, 1, 1)
        self.gridLayout.addWidget(self.tagsBox, 2, 1, 1, 2)
        self.descBox = QtGui.QGroupBox(Dialog)
        self.descBox.setCheckable(True)
        self.descBox.setObjectName("descBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.descBox)
        self.gridLayout_3.setMargin(10)
        self.gridLayout_3.setSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textEditDescription = QtGui.QPlainTextEdit(self.descBox)
        self.textEditDescription.setObjectName("textEditDescription")
        self.gridLayout_3.addWidget(self.textEditDescription, 0, 0, 1, 5)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 2, 0, 1, 3)
        self.pushButton_4 = QtGui.QPushButton(self.descBox)
        self.pushButton_4.setEnabled(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 2, 4, 1, 1)
        self.desc_mergeButton = QtGui.QPushButton(self.descBox)
        self.desc_mergeButton.setEnabled(True)
        self.desc_mergeButton.setObjectName("desc_mergeButton")
        self.gridLayout_3.addWidget(self.desc_mergeButton, 2, 3, 1, 1)
        self.gridLayout.addWidget(self.descBox, 3, 1, 1, 2)
        self.groupBox = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setMargin(10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textEditMeta = QtGui.QPlainTextEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditMeta.sizePolicy().hasHeightForWidth())
        self.textEditMeta.setSizePolicy(sizePolicy)
        self.textEditMeta.setMinimumSize(QtCore.QSize(0, 0))
        self.textEditMeta.setFrameShape(QtGui.QFrame.NoFrame)
        self.textEditMeta.setReadOnly(True)
        self.textEditMeta.setObjectName("textEditMeta")
        self.gridLayout_4.addWidget(self.textEditMeta, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 1, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL("clicked()"), self.textEditDescription.clear)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL("clicked()"), self.lineEditTags.clear)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.tagsBox.setTitle(QtGui.QApplication.translate("Dialog", "Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.tags_mergeButton.setText(QtGui.QApplication.translate("Dialog", "Merge current", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Dialog", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.descBox.setTitle(QtGui.QApplication.translate("Dialog", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("Dialog", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.desc_mergeButton.setText(QtGui.QApplication.translate("Dialog", "Merge current", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "/Users/johannes/path/to/long/soundfile/test.wav", None, QtGui.QApplication.UnicodeUTF8))

