# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created: Sat Jan  2 20:51:57 2010
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(506, 377)
        self.gridLayout = QtGui.QGridLayout(SettingsDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtGui.QTabWidget(SettingsDialog)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.treeView = QtGui.QTreeView(self.tab_4)
        self.treeView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeView.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.treeView.setIndentation(0)
        self.treeView.setObjectName("treeView")
        self.gridLayout_5.addWidget(self.treeView, 0, 0, 1, 5)
        self.buttonEdit = QtGui.QPushButton(self.tab_4)
        self.buttonEdit.setObjectName("buttonEdit")
        self.gridLayout_5.addWidget(self.buttonEdit, 1, 0, 1, 1)
        self.buttonRescan = QtGui.QPushButton(self.tab_4)
        self.buttonRescan.setObjectName("buttonRescan")
        self.gridLayout_5.addWidget(self.buttonRescan, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 1, 2, 1, 1)
        self.buttonAdd_4 = QtGui.QPushButton(self.tab_4)
        self.buttonAdd_4.setAutoDefault(False)
        self.buttonAdd_4.setDefault(True)
        self.buttonAdd_4.setObjectName("buttonAdd_4")
        self.gridLayout_5.addWidget(self.buttonAdd_4, 1, 3, 1, 1)
        self.buttonDelete_4 = QtGui.QPushButton(self.tab_4)
        self.buttonDelete_4.setObjectName("buttonDelete_4")
        self.gridLayout_5.addWidget(self.buttonDelete_4, 1, 4, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listWidget = QtGui.QListWidget(self.tab)
        self.listWidget.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_2.addWidget(self.listWidget, 0, 0, 1, 3)
        self.buttonDelete = QtGui.QPushButton(self.tab)
        self.buttonDelete.setObjectName("buttonDelete")
        self.gridLayout_2.addWidget(self.buttonDelete, 1, 2, 1, 1)
        self.buttonAdd = QtGui.QPushButton(self.tab)
        self.buttonAdd.setObjectName("buttonAdd")
        self.gridLayout_2.addWidget(self.buttonAdd, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.listWidget_2 = QtGui.QListWidget(self.tab_2)
        self.listWidget_2.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.listWidget_2.setObjectName("listWidget_2")
        self.gridLayout_3.addWidget(self.listWidget_2, 0, 0, 1, 3)
        spacerItem2 = QtGui.QSpacerItem(171, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 0, 1, 1)
        self.buttonAdd_2 = QtGui.QPushButton(self.tab_2)
        self.buttonAdd_2.setObjectName("buttonAdd_2")
        self.gridLayout_3.addWidget(self.buttonAdd_2, 1, 1, 1, 1)
        self.buttonDelete_2 = QtGui.QPushButton(self.tab_2)
        self.buttonDelete_2.setObjectName("buttonDelete_2")
        self.gridLayout_3.addWidget(self.buttonDelete_2, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.listWidget_3 = QtGui.QListWidget(self.tab_3)
        self.listWidget_3.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.listWidget_3.setAlternatingRowColors(False)
        self.listWidget_3.setObjectName("listWidget_3")
        QtGui.QListWidgetItem(self.listWidget_3)
        QtGui.QListWidgetItem(self.listWidget_3)
        self.gridLayout_4.addWidget(self.listWidget_3, 0, 0, 1, 3)
        spacerItem3 = QtGui.QSpacerItem(171, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 1, 0, 1, 1)
        self.buttonAdd_3 = QtGui.QPushButton(self.tab_3)
        self.buttonAdd_3.setObjectName("buttonAdd_3")
        self.gridLayout_4.addWidget(self.buttonAdd_3, 1, 1, 1, 1)
        self.buttonDelete_3 = QtGui.QPushButton(self.tab_3)
        self.buttonDelete_3.setObjectName("buttonDelete_3")
        self.gridLayout_4.addWidget(self.buttonDelete_3, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)

        self.retranslateUi(SettingsDialog)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        SettingsDialog.setWindowTitle(QtGui.QApplication.translate("SettingsDialog", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonEdit.setText(QtGui.QApplication.translate("SettingsDialog", "Edit...", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonRescan.setText(QtGui.QApplication.translate("SettingsDialog", "Rescan", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonAdd_4.setText(QtGui.QApplication.translate("SettingsDialog", "Add...", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonDelete_4.setText(QtGui.QApplication.translate("SettingsDialog", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("SettingsDialog", "Repositories", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonDelete.setText(QtGui.QApplication.translate("SettingsDialog", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonAdd.setText(QtGui.QApplication.translate("SettingsDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("SettingsDialog", "Applications", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonAdd_2.setText(QtGui.QApplication.translate("SettingsDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonDelete_2.setText(QtGui.QApplication.translate("SettingsDialog", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("SettingsDialog", "Formats", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.listWidget_3.isSortingEnabled()
        self.listWidget_3.setSortingEnabled(False)
        self.listWidget_3.item(0).setText(QtGui.QApplication.translate("SettingsDialog", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_3.item(1).setText(QtGui.QApplication.translate("SettingsDialog", "test2", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_3.setSortingEnabled(__sortingEnabled)
        self.buttonAdd_3.setText(QtGui.QApplication.translate("SettingsDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonDelete_3.setText(QtGui.QApplication.translate("SettingsDialog", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("SettingsDialog", "Folders", None, QtGui.QApplication.UnicodeUTF8))

